### ISSUE TITLE
Any update for Laravel 10 + Inertia 1.0? please...

### ISSUE THREAD

**Issue by isiungk** [7nohe/laravel-inertia-vue-app#1]

**Comment by 7nohe** [comment]
@iguojun 
You can refer to Inertia 1.0 [here](https://github.com/7nohe/laravel-typegen/tree/main/examples/laravel9-app). 
As for Laravel 10, I don't think it is much different from Laravel 9.

**Comment by isiungk** [comment]
> @iguojun You can refer to Inertia 1.0 [here](https://github.com/7nohe/laravel-typegen/tree/main/examples/laravel9-app). As for Laravel 10, I don't think it is much different from Laravel 9.

Appreciate your taking the time!
